### ISSUE TITLE
Error with message: `Cannot add event after closing`

### ISSUE THREAD

**Issue by DanMossa** [supabase/supabase-flutter#369]
**Describe the bug**
My app throws during launch with the following error:

```
Bad state: Cannot add event after closing

pid: 3709, tid: 7519, name 1.ui
os: android arch: arm64 comp: yes sim: no
build_id: 'bca64abfa56f32c731bb8f1c51cf314a'
isolate_dso_base: 79f9b44000, vm_dso_base: 79f9b44000
isolate_instructions: 79f9d71980, vm_instructions: 79f9d6c000
#0      _StreamController.add (dart:async/stream_controller.dart:595:24)
#1      _CompleterSink.add (package:web_socket_channel/src/sink_completer.dart:90:27)
#2      RealtimeClient.push.callback.<anonymous closure> (package:realtime_client/src/realtime_client.dart:252:55)
#3      new RealtimeClient.<anonymous closure> (package:realtime_client/src/realtime_client.dart:98:21)
#4      RealtimeClient.push.callback (package:realtime_client/src/realtime_client.dart:252:13)
#5      RealtimeClient.push (package:realtime_client/src/realtime_client.dart:269:9)
#6      Push.send (package:realtime_client/src/push.dart:57:36)
#7      Push.resend (package:realtime_client/src/push.dart:48:5)
#8      RealtimeChannel.rejoin (package:realtime_client/src/realtime_channel.dart:491:14)
#9      RealtimeChannel.rejoinUntilConnected (package:realtime_client/src/realtime_channel.dart:177:7)
#10     new RealtimeChannel.<anonymous closure> (package:realtime_client/src/realtime_channel.dart:132:37)
#11     RetryTimer.scheduleTimeout.<anonymous closure> (package:realtime_client/src/retry_timer.dart:46:15)
#12     _rootRun (dart:async/zone.dart:1390:47)
#13     _rootRun (dart:async/zone.dart:1389:1)
#14     _ZoneDelegate.run (dart:async/zone.dart:951:19)
#15     AsyncAction._run (package:mobx/src/api/async/async_action.dart:43:29)
#16     AsyncAction._run (package:mobx/src/api/async/async_action.dart:40:3)
#17     _ZoneDelegate.run (dart:async/zone.dart:951:19)
    #17 abs 00000079fa2ee7c7
virt 00000000007aa7c7 _kDartIsolateSnapshotInstructions+0x57ce47
#18     AsyncAction._run (package:mobx/src/api/async/async_action.dart:40:3)
#19     _CustomZone.run (dart:async/zone.dart:1300:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:1208:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248:23)
#22     _rootRun (dart:async/zone.dart:1398:13)
#23     _rootRun (dart:async/zone.dart:1389:1)
#24     _ZoneDelegate.run (dart:async/zone.dart:951:19)
#25     AsyncAction._run (package:mobx/src/api/async/async_action.dart:43:29)
#26     AsyncAction._run (package:mobx/src/api/async/async_action.dart:40:3)
#27     _ZoneDelegate.run (dart:async/zone.dart:951:19)
#28     AsyncAction._run (package:mobx/src/api/async/async_action.dart:43:29)
#29     AsyncAction._run (package:mobx/src/api/async/async_action.dart:40:3)
#30     _CustomZone.run (dart:async/zone.dart:1300:19)
#31     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1232:23)
#32     TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:420:15)
#33     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#34     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#35     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:419:3)
#36     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

Seems to be related to isolates?

**Comment by DanMossa** [comment]
Just got another error with the message: 
```
WebSocketException: Connection to '<SUPABASE URL>' was not upgraded to websocket
```

**Comment by DanMossa** [comment]
Some other info:
This doesn't happen on iOS, but only on Android. And The error seems to trigger when my app disconnects from internet for a little while.
I can't seem to figure out where to put a try-catch to solve it.

```
I/flutter (14690): [2023-03-05 20:28:25.874144 | Catcher | INFO] ---------- ERROR ----------
I/flutter (14690): [2023-03-05 20:28:25.874307 | Catcher | INFO] SocketException: Failed host lookup: 'khzlfnfbuzugj.supabase.co' (OS Error: No address associated with hostname, errno = 7)
I/flutter (14690): [2023-03-05 20:28:25.874408 | Catcher | INFO] 
I/flutter (14690): [2023-03-05 20:28:25.874505 | Catcher | INFO] ------- STACK TRACE -------
I/flutter (14690): [2023-03-05 20:28:25.875460 | Catcher | INFO] #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:694:35)
I/flutter (14690): [2023-03-05 20:28:25.875610 | Catcher | INFO] #1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1855:26)
I/flutter (14690): [2023-03-05 20:28:25.875718 | Catcher | INFO] #2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
I/flutter (14690): [2023-03-05 20:28:25.875817 | Catcher | INFO] #3      RawSecureSocket.startConnect (dart:io/secure_socket.dart:297:22)
I/flutter (14690): [2023-03-05 20:28:25.875913 | Catcher | INFO] #4      SecureSocket.startConnect (dart:io/secure_socket.dart:77:28)
I/flutter (14690): [2023-03-05 20:28:25.876010 | Catcher | INFO] #5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2462:26)
I/flutter (14690): [2023-03-05 20:28:25.876156 | Catcher | INFO] #6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2906:12)
I/flutter (14690): [2023-03-05 20:28:25.876254 | Catcher | INFO] #7      _HttpClient._getConnection (dart:_http/http_impl.dart:2911:12)
I/flutter (14690): [2023-03-05 20:28:25.876360 | Catcher | INFO] #8      _HttpClient._openUrl (dart:_http/http_impl.dart:2766:12)
I/flutter (14690): [2023-03-05 20:28:25.876468 | Catcher | INFO] #9      _HttpClient.openUrl (dart:_http/http_impl.dart:2604:7)
I/flutter (14690): [2023-03-05 20:28:25.876570 | Catcher | INFO] #10     _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1021:42)
I/flutter (14690): [2023-03-05 20:28:25.876670 | Catcher | INFO] #11     WebSocket.connect (dart:_http/websocket.dart:320:22)
I/flutter (14690): [2023-03-05 20:28:25.876766 | Catcher | INFO] #12     new IOWebSocketChannel.connect (package:web_socket_channel/io.dart:80:28)
I/flutter (14690): [2023-03-05 20:28:25.876860 | Catcher | INFO] #13     createWebSocketClient (package:realtime_client/src/websocket/websocket_io.dart:8:29)
I/flutter (14690): [2023-03-05 20:28:25.876958 | Catcher | INFO] #14     RealtimeClient.connect (package:realtime_client/src/realtime_client.dart:119:23)
I/flutter (14690): [2023-03-05 20:28:25.877062 | Catcher | INFO] #15     new RealtimeClient.<anonymous closure> (package:realtime_client/src/realtime_client.dart:105:9)
I/flutter (14690): [2023-03-05 20:28:25.877162 | Catcher | INFO] #16     RetryTimer.scheduleTimeout.<anonymous closure> (package:realtime_client/src/retry_timer.dart:46:15)
I/flutter (14690): [2023-03-05 20:28:25.877261 | Catcher | INFO] #17     _rootRun (dart:async/zone.dart:1390:47)
I/flutter (14690): [2023-03-05 20:28:25.877360 | Catcher | INFO] #18     _ZoneDelegate.run (dart:async/zone.dart:951:19)
I/flutter (14690): [2023-03-05 20:28:25.877457 | Catcher | INFO] #19     AsyncAction._run (package:mobx/src/api/async/async_action.dart:43:29)
I/flutter (14690): [2023-03-05 20:28:25.877575 | Catcher | INFO] #20     _ZoneDelegate.run (dart:async/zone.dart:951:19)
I/flutter (14690): [2023-03-05 20:28:25.877670 | Catcher | INFO] #21     AsyncAction._run (package:mobx/src/api/async/async_action.dart:43:29)
I/flutter (14690): [2023-03-05 20:28:25.877764 | Catcher | INFO] #22     _CustomZone.run (dart:async/zone.dart:1300:19)
I/flutter (14690): [2023-03-05 20:28:25.877863 | Catcher | INFO] #23     _CustomZone.runGuarded (dart:async/zone.dart:1208:7)
I/flutter (14690): [2023-03-05 20:28:25.877969 | Catcher | INFO] #24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248:23)
I/flutter (14690): [2023-03-05 20:28:25.878064 | Catcher | INFO] #25     _rootRun (dart:async/zone.dart:1398:13)
I/flutter (14690): [2023-03-05 20:28:25.878155 | Catcher | INFO] #26     _ZoneDelegate.run (dart:async/zone.dart:951:19)
I/flutter (14690): [2023-03-05 20:28:25.878244 | Catcher | INFO] #27     AsyncAction._run (package:mobx/src/api/async/async_action.dart:43:29)
I/flutter (14690): [2023-03-05 20:28:25.878334 | Catcher | INFO] #28     _ZoneDelegate.run (dart:async/zone.dart:951:19)
I/flutter (14690): [2023-03-05 20:28:25.878433 | Catcher | INFO] #29     AsyncAction._run (package:mobx/src/api/async/async_action.dart:43:29)
I/flutter (14690): [2023-03-05 20:28:25.878532 | Catcher | INFO] #30     _CustomZone.run (dart:async/zone.dart:1300:19)
I/flutter (14690): [2023-03-05 20:28:25.878641 | Catcher | INFO] #31     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1232:23)
I/flutter (14690): [2023-03-05 20:28:25.878742 | Catcher | INFO] #32     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
I/flutter (14690): [2023-03-05 20:28:25.878842 | Catcher | INFO] #33     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
```

**Comment by dshukertjr** [comment]
@DanMossa 
Nice! Yeah, error handling in general for real-time can use an improvements.

**Comment by Vinzent03** [comment]
@dshukertjr I'm currently on it, it's a bit tricky. https://github.com/supabase/realtime-dart/pull/62 In the current try it works afaik, but it makes connect async. Now trying a different approach.

**Comment by dshukertjr** [comment]
Thanks @Vinzent03 ! Always way ahead of me!

**Comment by DanMossa** [comment]
@Vinzent03  The only thing left to do is update this package to use the new supabase-dart ?

**Comment by Vinzent03** [comment]
@DanMossa  You should already be able to use the latest realtime version. Just run `flutter pub upgrade realtime_client`. There should not be a version conflict.

**Comment by DanMossa** [comment]
@Vinzent03 Ah, like override the dependency? Didn't think about that. Thank you!

**Comment by Vinzent03** [comment]
No need to override the dependency. Just the dependency

**Comment by Vinzent03** [comment]
@DanMossa This can be closed, right?

**Comment by DanMossa** [comment]
@Vinzent03 Yeah! I'll make a new ticket or reopen this one if something else appears.

Thanks!

**Comment by DanMossa** [comment]
@Vinzent03 

I believe the issue still exists.

I should either be able to catch the error, or the error shouldn't exist.

I believe what I could do is when the app is backgrounded, I can unsubscribe from the channels, and then when the app is foregrounded, the channels are resubscribed.

But I do think regardless the error should be catchable

**Comment by Vinzent03** [comment]
How exactly are you trying to catch the error, or how are you listening to errors? Which exact stack trace do you encounter?

**Comment by DanMossa** [comment]
```dart
  void subscribeToChat(
    String accountUserId, {
    required Future<bool> Function(dynamic payload, [dynamic ref]) onNewMessage,
  }) {
    if (isUserShadowBanned || isUserBanned) {
      return;
    }

    try {
      _supabase.channel('chat:$accountUserId').on(
        RealtimeListenTypes.postgresChanges,
        ChannelFilter(
          event: 'INSERT',
          schema: 'public',
          table: constants.Table.messages.name,
          // filter: Using RLS for selecting rows
        ),
        (payload, [ref]) async {
          final bool inserted = await onNewMessage(payload, ref);
          if (inserted) {
            _logService.info(
              'New message received: ${payload.toString()}',
              location: "subscribeToChat",
            );
          }
        },
      ).subscribe((String p0, [Object? p1]) {
        if (p1 == null) {
          _logService.info(p0, location: 'subscribeToChat');
        } else {
          _logService.error(p0, location: 'subscribeToChat', error: p1);
        }
      });
    } on Exception catch (e) {
      throw Exception("Error with subscribeToChat: ${e.toString()}");
    }
  }
```

The catch block is never being hit. My stack traces are decrypted and I won't be able to post a decrypted stack trace until the end of March, but it should be similar/the same as the one in the opening post.
