### ISSUE TITLE
Un-catchable "Access token refresh retry limit exceeded" error after resuming app too many times.

### ISSUE THREAD

**Issue by SynSzakala** [supabase/supabase-flutter#396]
Supabase Auth registers a listener for `AppLifecycleState.resumed` in which it attempts to refresh the access token. `GoTrueClient` imposes a limit of 10 refreshes per session. This causes an un-catchable exception to be thrown when app is paused and resumed more than 10 times:

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: AuthException(message: Access token refresh retry limit exceeded., statusCode: null)
#0      GoTrueClient._setTokenRefreshTimer (package:gotrue/src/gotrue_client.dart:628:49)
#1      GoTrueClient._saveSession (package:gotrue/src/gotrue_client.dart:603:9)
#2      GoTrueClient.recoverSession (package:gotrue/src/gotrue_client.dart:559:7)
#3      SupabaseAuth._recoverSupabaseSession (package:supabase_flutter/src/supabase_auth.dart:170:43)
<asynchronous suspension>
```

Further resumes cause the same exception. I haven't checked if the access token is actually refreshed before it expires, but from what I see in the code, it won't be.
Mentioned exception is thrown in code called by Flutter's `WidgetsBinding` so it's basically un-catchable, even when wrapping the `Supabase.initialize` call in a `runZonedGuarded`. It forced us to explicitly whitelist the exception in our global error handling/reporting system.

**To Reproduce**

1. Run the example app on any device without any changes. 
2. Sign in.
3. Send the app to background and bring it back up to foreground. Repeat 10 times.
4. `Unhandled exception: AuthException(...)` will appear in the logs after every next pause/resume cycle.

**Expected behavior**

Exception should not be thrown and access token management should work as usual.

**Version (please complete the following information):**
 - `supabase_flutter`: 1.5.0

**Additional context**

Full logs:
```
flutter: **** onAuthStateChange: AuthChangeEvent.signedIn
flutter: {"currentSession":{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjc4NTY0MDEzLCJzdWIiOiJhNDkyODI1ZS1jNzljLTRjOTQtYWJlNi1kMmU1YzczZjg5YzUiLCJlbWFpbCI6InNrZGpkamRqQG5pZXBvZGFtLnBsIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE2Nzg1NjA0MTN9XSwic2Vzc2lvbl9pZCI6IjFhNjQ1ZThhLWU0YmEtNDc5Zi1hMDRlLTNmMzM4NDA1YmEzZCJ9.lSWFrJVYS1TbGJppRMVQhHpTZ37zbXOmo3PEwdGhLfg","expires_in":3600,"refresh_token":"saxOvq_zwR8hDgq6072Z8w","token_type":"bearer","provider_token":null,"provider_refresh_token":null,"user":{"id":"a492825e-c79c-4c94-abe6-d2e5c73f89c5","app_metadata":{"provider":"email","providers":["email"]},"user_metadata":{},"aud":"authenticated","email":"skdjdjdj@niepodam.pl","phone":"","created_at":"2023-03-11T18:46:53.579018Z","confirmed_at":null,"email_confirmed_at":"2023-03-11T18:46:53.584046345Z","phone_confirmed_at":null,"last_sign_in_at":"2023-03-11T18:46:53.586510336Z","role":"authenticated","updated_at":"2023-03-11T18:46:53.588571Z"}},"expiresAt":1678564013}
[Snapshotting] Snapshotting a view (0x115016e00, UIKeyboardImpl) that is not in a visible window requires afterScreenUpdates:YES.
flutter: **** onAuthStateChange: AuthChangeEvent.signedIn
flutter: {"currentSession":{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjc4NTY0MDEzLCJzdWIiOiJhNDkyODI1ZS1jNzljLTRjOTQtYWJlNi1kMmU1YzczZjg5YzUiLCJlbWFpbCI6InNrZGpkamRqQG5pZXBvZGFtLnBsIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE2Nzg1NjA0MTN9XSwic2Vzc2lvbl9pZCI6IjFhNjQ1ZThhLWU0YmEtNDc5Zi1hMDRlLTNmMzM4NDA1YmEzZCJ9.lSWFrJVYS1TbGJppRMVQhHpTZ37zbXOmo3PEwdGhLfg","expires_in":3600,"refresh_token":"saxOvq_zwR8hDgq6072Z8w","token_type":"bearer","provider_token":null,"provider_refresh_token":null,"user":{"id":"a492825e-c79c-4c94-abe6-d2e5c73f89c5","app_metadata":{"provider":"email","providers":["email"]},"user_metadata":{},"aud":"authenticated","email":"skdjdjdj@niepodam.pl","phone":"","created_at":"2023-03-11T18:46:53.579018Z","confirmed_at":null,"email_confirmed_at":"2023-03-11T18:46:53.584046345Z","phone_confirmed_at":null,"last_sign_in_at":"2023-03-11T18:46:53.586510336Z","role":"authenticated","updated_at":"2023-03-11T18:46:53.588571Z"}},"expiresAt":1678564013}
[Snapshotting] Snapshotting a view (0x115032a00, UIKeyboardImpl) that has not been rendered at least once requires afterScreenUpdates:YES.
flutter: **** onAuthStateChange: AuthChangeEvent.signedIn
flutter: {"currentSession":{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjc4NTY0MDEzLCJzdWIiOiJhNDkyODI1ZS1jNzljLTRjOTQtYWJlNi1kMmU1YzczZjg5YzUiLCJlbWFpbCI6InNrZGpkamRqQG5pZXBvZGFtLnBsIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE2Nzg1NjA0MTN9XSwic2Vzc2lvbl9pZCI6IjFhNjQ1ZThhLWU0YmEtNDc5Zi1hMDRlLTNmMzM4NDA1YmEzZCJ9.lSWFrJVYS1TbGJppRMVQhHpTZ37zbXOmo3PEwdGhLfg","expires_in":3600,"refresh_token":"saxOvq_zwR8hDgq6072Z8w","token_type":"bearer","provider_token":null,"provider_refresh_token":null,"user":{"id":"a492825e-c79c-4c94-abe6-d2e5c73f89c5","app_metadata":{"provider":"email","providers":["email"]},"user_metadata":{},"aud":"authenticated","email":"skdjdjdj@niepodam.pl","phone":"","created_at":"2023-03-11T18:46:53.579018Z","confirmed_at":null,"email_confirmed_at":"2023-03-11T18:46:53.584046345Z","phone_confirmed_at":null,"last_sign_in_at":"2023-03-11T18:46:53.586510336Z","role":"authenticated","updated_at":"2023-03-11T18:46:53.588571Z"}},"expiresAt":1678564013}
[Snapshotting] Snapshotting a view (0x115027600, UIKeyboardImpl) that has not been rendered at least once requires afterScreenUpdates:YES.
flutter: **** onAuthStateChange: AuthChangeEvent.signedIn
flutter: {"currentSession":{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjc4NTY0MDEzLCJzdWIiOiJhNDkyODI1ZS1jNzljLTRjOTQtYWJlNi1kMmU1YzczZjg5YzUiLCJlbWFpbCI6InNrZGpkamRqQG5pZXBvZGFtLnBsIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE2Nzg1NjA0MTN9XSwic2Vzc2lvbl9pZCI6IjFhNjQ1ZThhLWU0YmEtNDc5Zi1hMDRlLTNmMzM4NDA1YmEzZCJ9.lSWFrJVYS1TbGJppRMVQhHpTZ37zbXOmo3PEwdGhLfg","expires_in":3600,"refresh_token":"saxOvq_zwR8hDgq6072Z8w","token_type":"bearer","provider_token":null,"provider_refresh_token":null,"user":{"id":"a492825e-c79c-4c94-abe6-d2e5c73f89c5","app_metadata":{"provider":"email","providers":["email"]},"user_metadata":{},"aud":"authenticated","email":"skdjdjdj@niepodam.pl","phone":"","created_at":"2023-03-11T18:46:53.579018Z","confirmed_at":null,"email_confirmed_at":"2023-03-11T18:46:53.584046345Z","phone_confirmed_at":null,"last_sign_in_at":"2023-03-11T18:46:53.586510336Z","role":"authenticated","updated_at":"2023-03-11T18:46:53.588571Z"}},"expiresAt":1678564013}
[Snapshotting] Snapshotting a view (0x115841000, UIKeyboardImpl) that has not been rendered at least once requires afterScreenUpdates:YES.
flutter: **** onAuthStateChange: AuthChangeEvent.signedIn
flutter: {"currentSession":{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjc4NTY0MDEzLCJzdWIiOiJhNDkyODI1ZS1jNzljLTRjOTQtYWJlNi1kMmU1YzczZjg5YzUiLCJlbWFpbCI6InNrZGpkamRqQG5pZXBvZGFtLnBsIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE2Nzg1NjA0MTN9XSwic2Vzc2lvbl9pZCI6IjFhNjQ1ZThhLWU0YmEtNDc5Zi1hMDRlLTNmMzM4NDA1YmEzZCJ9.lSWFrJVYS1TbGJppRMVQhHpTZ37zbXOmo3PEwdGhLfg","expires_in":3600,"refresh_token":"saxOvq_zwR8hDgq6072Z8w","token_type":"bearer","provider_token":null,"provider_refresh_token":null,"user":{"id":"a492825e-c79c-4c94-abe6-d2e5c73f89c5","app_metadata":{"provider":"email","providers":["email"]},"user_metadata":{},"aud":"authenticated","email":"skdjdjdj@niepodam.pl","phone":"","created_at":"2023-03-11T18:46:53.579018Z","confirmed_at":null,"email_confirmed_at":"2023-03-11T18:46:53.584046345Z","phone_confirmed_at":null,"last_sign_in_at":"2023-03-11T18:46:53.586510336Z","role":"authenticated","updated_at":"2023-03-11T18:46:53.588571Z"}},"expiresAt":1678564013}
[Snapshotting] Snapshotting a view (0x11581a600, UIKeyboardImpl) that has not been rendered at least once requires afterScreenUpdates:YES.
flutter: **** onAuthStateChange: AuthChangeEvent.signedIn
flutter: {"currentSession":{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjc4NTY0MDEzLCJzdWIiOiJhNDkyODI1ZS1jNzljLTRjOTQtYWJlNi1kMmU1YzczZjg5YzUiLCJlbWFpbCI6InNrZGpkamRqQG5pZXBvZGFtLnBsIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE2Nzg1NjA0MTN9XSwic2Vzc2lvbl9pZCI6IjFhNjQ1ZThhLWU0YmEtNDc5Zi1hMDRlLTNmMzM4NDA1YmEzZCJ9.lSWFrJVYS1TbGJppRMVQhHpTZ37zbXOmo3PEwdGhLfg","expires_in":3600,"refresh_token":"saxOvq_zwR8hDgq6072Z8w","token_type":"bearer","provider_token":null,"provider_refresh_token":null,"user":{"id":"a492825e-c79c-4c94-abe6-d2e5c73f89c5","app_metadata":{"provider":"email","providers":["email"]},"user_metadata":{},"aud":"authenticated","email":"skdjdjdj@niepodam.pl","phone":"","created_at":"2023-03-11T18:46:53.579018Z","confirmed_at":null,"email_confirmed_at":"2023-03-11T18:46:53.584046345Z","phone_confirmed_at":null,"last_sign_in_at":"2023-03-11T18:46:53.586510336Z","role":"authenticated","updated_at":"2023-03-11T18:46:53.588571Z"}},"expiresAt":1678564013}
[Snapshotting] Snapshotting a view (0x115841000, UIKeyboardImpl) that has not been rendered at least once requires afterScreenUpdates:YES.
flutter: **** onAuthStateChange: AuthChangeEvent.signedIn
flutter: {"currentSession":{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjc4NTY0MDEzLCJzdWIiOiJhNDkyODI1ZS1jNzljLTRjOTQtYWJlNi1kMmU1YzczZjg5YzUiLCJlbWFpbCI6InNrZGpkamRqQG5pZXBvZGFtLnBsIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE2Nzg1NjA0MTN9XSwic2Vzc2lvbl9pZCI6IjFhNjQ1ZThhLWU0YmEtNDc5Zi1hMDRlLTNmMzM4NDA1YmEzZCJ9.lSWFrJVYS1TbGJppRMVQhHpTZ37zbXOmo3PEwdGhLfg","expires_in":3600,"refresh_token":"saxOvq_zwR8hDgq6072Z8w","token_type":"bearer","provider_token":null,"provider_refresh_token":null,"user":{"id":"a492825e-c79c-4c94-abe6-d2e5c73f89c5","app_metadata":{"provider":"email","providers":["email"]},"user_metadata":{},"aud":"authenticated","email":"skdjdjdj@niepodam.pl","phone":"","created_at":"2023-03-11T18:46:53.579018Z","confirmed_at":null,"email_confirmed_at":"2023-03-11T18:46:53.584046345Z","phone_confirmed_at":null,"last_sign_in_at":"2023-03-11T18:46:53.586510336Z","role":"authenticated","updated_at":"2023-03-11T18:46:53.588571Z"}},"expiresAt":1678564013}
[Snapshotting] Snapshotting a view (0x115ccee00, UIKeyboardImpl) that has not been rendered at least once requires afterScreenUpdates:YES.
flutter: **** onAuthStateChange: AuthChangeEvent.signedIn
flutter: {"currentSession":{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjc4NTY0MDEzLCJzdWIiOiJhNDkyODI1ZS1jNzljLTRjOTQtYWJlNi1kMmU1YzczZjg5YzUiLCJlbWFpbCI6InNrZGpkamRqQG5pZXBvZGFtLnBsIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE2Nzg1NjA0MTN9XSwic2Vzc2lvbl9pZCI6IjFhNjQ1ZThhLWU0YmEtNDc5Zi1hMDRlLTNmMzM4NDA1YmEzZCJ9.lSWFrJVYS1TbGJppRMVQhHpTZ37zbXOmo3PEwdGhLfg","expires_in":3600,"refresh_token":"saxOvq_zwR8hDgq6072Z8w","token_type":"bearer","provider_token":null,"provider_refresh_token":null,"user":{"id":"a492825e-c79c-4c94-abe6-d2e5c73f89c5","app_metadata":{"provider":"email","providers":["email"]},"user_metadata":{},"aud":"authenticated","email":"skdjdjdj@niepodam.pl","phone":"","created_at":"2023-03-11T18:46:53.579018Z","confirmed_at":null,"email_confirmed_at":"2023-03-11T18:46:53.584046345Z","phone_confirmed_at":null,"last_sign_in_at":"2023-03-11T18:46:53.586510336Z","role":"authenticated","updated_at":"2023-03-11T18:46:53.588571Z"}},"expiresAt":1678564013}
[Snapshotting] Snapshotting a view (0x115ccee00, UIKeyboardImpl) that has not been rendered at least once requires afterScreenUpdates:YES.
flutter: **** onAuthStateChange: AuthChangeEvent.signedIn
flutter: {"currentSession":{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjc4NTY0MDEzLCJzdWIiOiJhNDkyODI1ZS1jNzljLTRjOTQtYWJlNi1kMmU1YzczZjg5YzUiLCJlbWFpbCI6InNrZGpkamRqQG5pZXBvZGFtLnBsIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE2Nzg1NjA0MTN9XSwic2Vzc2lvbl9pZCI6IjFhNjQ1ZThhLWU0YmEtNDc5Zi1hMDRlLTNmMzM4NDA1YmEzZCJ9.lSWFrJVYS1TbGJppRMVQhHpTZ37zbXOmo3PEwdGhLfg","expires_in":3600,"refresh_token":"saxOvq_zwR8hDgq6072Z8w","token_type":"bearer","provider_token":null,"provider_refresh_token":null,"user":{"id":"a492825e-c79c-4c94-abe6-d2e5c73f89c5","app_metadata":{"provider":"email","providers":["email"]},"user_metadata":{},"aud":"authenticated","email":"skdjdjdj@niepodam.pl","phone":"","created_at":"2023-03-11T18:46:53.579018Z","confirmed_at":null,"email_confirmed_at":"2023-03-11T18:46:53.584046345Z","phone_confirmed_at":null,"last_sign_in_at":"2023-03-11T18:46:53.586510336Z","role":"authenticated","updated_at":"2023-03-11T18:46:53.588571Z"}},"expiresAt":1678564013}
[Snapshotting] Snapshotting a view (0x1150d5600, UIKeyboardImpl) that has not been rendered at least once requires afterScreenUpdates:YES.
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: AuthException(message: Access token refresh retry limit exceeded., statusCode: null)
#0      GoTrueClient._setTokenRefreshTimer (package:gotrue/src/gotrue_client.dart:628:49)
#1      GoTrueClient._saveSession (package:gotrue/src/gotrue_client.dart:603:9)
#2      GoTrueClient.recoverSession (package:gotrue/src/gotrue_client.dart:559:7)
#3      SupabaseAuth._recoverSupabaseSession (package:supabase_flutter/src/supabase_auth.dart:170:43)
<asynchronous suspension>
flutter: **** onAuthStateChange: AuthChangeEvent.signedIn
flutter: {"currentSession":{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjc4NTY0MDEzLCJzdWIiOiJhNDkyODI1ZS1jNzljLTRjOTQtYWJlNi1kMmU1YzczZjg5YzUiLCJlbWFpbCI6InNrZGpkamRqQG5pZXBvZGFtLnBsIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE2Nzg1NjA0MTN9XSwic2Vzc2lvbl9pZCI6IjFhNjQ1ZThhLWU0YmEtNDc5Zi1hMDRlLTNmMzM4NDA1YmEzZCJ9.lSWFrJVYS1TbGJppRMVQhHpTZ37zbXOmo3PEwdGhLfg","expires_in":3600,"refresh_token":"saxOvq_zwR8hDgq6072Z8w","token_type":"bearer","provider_token":null,"provider_refresh_token":null,"user":{"id":"a492825e-c79c-4c94-abe6-d2e5c73f89c5","app_metadata":{"provider":"email","providers":["email"]},"user_metadata":{},"aud":"authenticated","email":"skdjdjdj@niepodam.pl","phone":"","created_at":"2023-03-11T18:46:53.579018Z","confirmed_at":null,"email_confirmed_at":"2023-03-11T18:46:53.584046345Z","phone_confirmed_at":null,"last_sign_in_at":"2023-03-11T18:46:53.586510336Z","role":"authenticated","updated_at":"2023-03-11T18:46:53.588571Z"}},"expiresAt":1678564013}
[Snapshotting] Snapshotting a view (0x115841000, UIKeyboardImpl) that has not been rendered at least once requires afterScreenUpdates:YES.
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: AuthException(message: Access token refresh retry limit exceeded., statusCode: null)
#0      GoTrueClient._setTokenRefreshTimer (package:gotrue/src/gotrue_client.dart:628:49)
#1      GoTrueClient._saveSession (package:gotrue/src/gotrue_client.dart:603:9)
#2      GoTrueClient.recoverSession (package:gotrue/src/gotrue_client.dart:559:7)
#3      SupabaseAuth._recoverSupabaseSession (package:supabase_flutter/src/supabase_auth.dart:170:43)
<asynchronous suspension>
flutter: **** onAuthStateChange: AuthChangeEvent.signedIn
flutter: {"currentSession":{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjc4NTY0MDEzLCJzdWIiOiJhNDkyODI1ZS1jNzljLTRjOTQtYWJlNi1kMmU1YzczZjg5YzUiLCJlbWFpbCI6InNrZGpkamRqQG5pZXBvZGFtLnBsIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE2Nzg1NjA0MTN9XSwic2Vzc2lvbl9pZCI6IjFhNjQ1ZThhLWU0YmEtNDc5Zi1hMDRlLTNmMzM4NDA1YmEzZCJ9.lSWFrJVYS1TbGJppRMVQhHpTZ37zbXOmo3PEwdGhLfg","expires_in":3600,"refresh_token":"saxOvq_zwR8hDgq6072Z8w","token_type":"bearer","provider_token":null,"provider_refresh_token":null,"user":{"id":"a492825e-c79c-4c94-abe6-d2e5c73f89c5","app_metadata":{"provider":"email","providers":["email"]},"user_metadata":{},"aud":"authenticated","email":"skdjdjdj@niepodam.pl","phone":"","created_at":"2023-03-11T18:46:53.579018Z","confirmed_at":null,"email_confirmed_at":"2023-03-11T18:46:53.584046345Z","phone_confirmed_at":null,"last_sign_in_at":"2023-03-11T18:46:53.586510336Z","role":"authenticated","updated_at":"2023-03-11T18:46:53.588571Z"}},"expiresAt":1678564013}
```

**Comment by DanMossa** [comment]
@Vinzent03 is working on this :)

**Comment by SynSzakala** [comment]
Ah, haven't found it for some reason. Thanks for a quicki reply!
