### ISSUE TITLE
Error when listening to events

### ISSUE THREAD

**Issue by gcostaapps** [supabase/supabase-flutter#49]
# Bug report

## Describe the bug

Sometimes when I'm subscribed to a table in my database and reveive new events I got this error, but couldn't find the reason to it. Any tips where to search?

```
E/flutter ( 4940): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Concurrent modification during iteration: Instance(length:18) of '_GrowableList'.
E/flutter ( 4940): #0      ListIterator.moveNext (dart:_internal/iterable.dart:336:7)
E/flutter ( 4940): #1      WhereIterator.moveNext (dart:_internal/iterable.dart:438:22)
E/flutter ( 4940): #2      Iterable.forEach (dart:core/iterable.dart:279:23)
E/flutter ( 4940): #3      RealtimeClient.onConnMessage.<anonymous closure> (package:realtime_client/src/realtime_client.dart:264:60)
E/flutter ( 4940): #4      new RealtimeClient.<anonymous closure> (package:realtime_client/src/realtime_client.dart:86:21)
E/flutter ( 4940): #5      RealtimeClient.onConnMessage (package:realtime_client/src/realtime_client.dart:249:11)
E/flutter ( 4940): #6      RealtimeClient.connect.<anonymous closure> (package:realtime_client/src/realtime_client.dart:108:11)
E/flutter ( 4940): #7      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 4940): #8      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 4940): #9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 4940): #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter ( 4940): #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 4940): #12     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter ( 4940): #13     _HandleErrorStream._handleData (dart:async/stream_pipe.dart:253:10)
E/flutter ( 4940): #14     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter ( 4940): #15     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 4940): #16     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 4940): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 4940): #18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter ( 4940): #19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 4940): #20     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
E/flutter ( 4940): #21     _StreamController._add (dart:async/stream_controller.dart:607:7)
E/flutter ( 4940): #22     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 4940): #23     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 4940): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 4940): #25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter ( 4940): #26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 4940): #27     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
E/flutter ( 4940): #28     _StreamController._add (dart:async/stream_controller.dart:607:7)
E/flutter ( 4940): #29     _StreamController.add (dart:async/stream_controller.dart:554:5)
E/flutter ( 4940): #30     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1150:21)
E/flutter ( 4940): #31     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 4940): #32     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 4940): #33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 4940): #34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter ( 4940): #35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 4940): #36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
E/flutter ( 4940): #37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
E/flutter ( 4940): #38     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
E/flutter ( 4940): #39     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
E/flutter ( 4940): #40     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
E/flutter ( 4940): #41     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 4940): #42     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 4940): #43     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 4940): #44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter ( 4940): #45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 4940): #46     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
E/flutter ( 4940): #47     _StreamController._add (dart:async/stream_controller.dart:607:7)
E/flutter ( 4940): #48     _StreamController.add (dart:async/stream_controller.dart:554:5)
E/flutter ( 4940): #49     _Socket._onData (dart:io-patch/socket_patch.dart:2166:41)
E/flutter ( 4940): #50     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 4940): #51     _CustomZone.runUnary (dart:async/zone.d
```

Running the last version of supabase_flutter

**Comment by dshukertjr** [comment]
Thanks for opening this issue @gcostaapps!

The error log is very helpful. Are you using the [`stream()`](https://supabase.com/docs/reference/dart/stream) method to listen to realtime events, or [`on().subscribe()`](https://supabase.com/docs/reference/dart/subscribe)?

Also, just not sure if it's related, but just in case, could you share the table definition of the table you are listening to?

**Comment by gcostaapps** [comment]
Hi @dshukertjr , I'm using `on().subscribe()` and I'm searching filtering for a specific id using 
`.from('liveLessonTeam:liveLesson_id=eq.${liveLesson.id}')`

The liveLessonTeam table is:

```
id: int8 (PK)
liveLesson_id: int8 (FK to liveLesson table)
answers: json[]
```

**Comment by dshukertjr** [comment]
Thank you @gcostaapps !

This is very helpful. Let me try to reproduce it and track down why the error is happening.
