### ISSUE TITLE
RealtimeSubscription Unhandled Exception: type 'Null' is not a subtype of type 'List<dynamic>' in type cast

### ISSUE THREAD

**Issue by offline-first** [supabase/supabase-flutter#50]
## Bug report

When I listen to realtime events, and insert data to table, the `supabase_realtime_payload.dart` throws this exception. 

```log
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'List<dynamic>' in type cast
#0      new SupabaseRealtimePayload.fromJson.<anonymous closure> (package:supabase/src/supabase_realtime_payload.dart:36:35)
#1      WhereIterator.moveNext (dart:_internal/iterable.dart:439:13)
#2      MappedIterator.moveNext (dart:_internal/iterable.dart:390:19)
#3      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#5      new List.of (dart:core-patch/array_patch.dart:50:28)
#6      Iterable.toList (dart:core/iterable.dart:388:12)
#7      new SupabaseRealtimePayload.fromJson (package:supabase/src/supabase_realtime_payload.dart:38:10)
#8      SupabaseRealtimeClient.on.<anonymous closure> (package:supabase/src/supabase_realtime_client.dart:35:57)
#9      RealtimeSubscription.trigger (package:realtime_client/src/realtime_subscription.dart:221:20)
#10     RealtimeClient.onConnMessage.<anonymous closure>.<anonymous closure> (package:realtime_client/src/realtime_client.dart:265:34)
#11     Iterable.forEach (dart:core/iterable.dart:279:35)
#12     RealtimeClient.onConnMessage.<anonymous closure> (package:realtime_client/src/realtime_client.dart:264:60)
#13     new RealtimeClient.<anonymous closure> (package:realtime_client/src/realtime_client.dart:86:21)
#14     RealtimeClient.onConnMessage (package:realtime_client/src/realtime_client.dart:249:11)
#15     RealtimeClient.connect.<anonymous closure> (package:realtime_client/src/realtime_client.dart:108:11)
#16     _rootRunUnary (dart:async/zone.dart:1436:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#21     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#22     _HandleErrorStream._handleData (dart:async/stream_pipe.dart:253:10)
#23     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#24     _rootRunUnary (dart:async/zone.dart:1436:47)
#25     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#29     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#30     _StreamController._add (dart:async/stream_controller.dart:607:7)
#31     _rootRunUnary (dart:async/zone.dart:1436:47)
#32     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#36     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#37     _StreamController._add (dart:async/stream_controller.dart:607:7)
#38     _StreamController.add (dart:async/stream_controller.dart:554:5)
#39     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1150:21)
#40     _rootRunUnary (dart:async/zone.dart:1436:47)
#41     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#45     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#46     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#47     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#48     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#49     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#50     _rootRunUnary (dart:async/zone.dart:1436:47)
#51     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#52     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#55     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#56     _StreamController._add (dart:async/stream_controller.dart:607:7)
#57     _StreamController.add (dart:async/stream_controller.dart:554:5)
#58     _Socket._onData (dart:io-patch/socket_patch.dart:2166:41)
#59     _rootRunUnary (dart:async/zone.dart:1436:47)
#60     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#61     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#62     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#63     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#64     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#65     _StreamController._add (dart:async/stream_controller.dart:607:7)
#66     _StreamController.add (dart:async/stream_controller.dart:554:5)
#67     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:991:19)
#68     _rootRun (dart:async/zone.dart:1420:47)
#69     _CustomZone.run (dart:async/zone.dart:1328:19)
#70     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#71     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#72     _rootRun (dart:async/zone.dart:1428:13)
#73     _CustomZone.run (dart:async/zone.dart:1328:19)
#74     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
#75     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#76     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
#77     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
#78     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

### Flutter 
```dart
// subscribe to messages
_messageListener = client
        .from('messages')
        .on(SupabaseEventTypes.insert, (payload) => print('newRecord:${payload.newRecord}'))
        .subscribe();
```

```dart
// insert message
addMessage(String message, int channelId)async{
    final response = await client
        .from('messages')
        .insert({ 'message' : message, 'user_id':  client.auth.currentUser!.id, 'channel_id': channelId})
        .execute();
  }
```

## plugin version:
- supabase: ^0.2.9
- flutter sdk: ">=2.12.0 <3.0.0"
- Platform: iOS 15.1

**Comment by bdlukaa** [comment]
https://github.com/supabase/supabase-dart/blob/main/lib/src/supabase_realtime_payload.dart#L35-L38

**Comment by offline-first** [comment]
Here is a fix:
```dart
final primaryKeys = (json['columns'] as List)
        .where((e) => (e['flags'] as List?)?.contains('key') == true)
        .map((e) => e['name'] as String)
        .toList();
```

**Comment by bdlukaa** [comment]
@dshukertjr what do you think?

**Comment by offline-first** [comment]
The error is not in supabase-flutter but in supabase-dart...
