### ISSUE TITLE
deleteUser returns a response with FormatException

### ISSUE THREAD

**Issue by Ben1980** [supabase/supabase-flutter#551]
I made an edge function that is calling `supabase.auth.admin.deletUser(....)`. It is deleting the user as expected but it returns just 
```
"User deleted: {
  "user": {}
}"
```
which is then leading to an format exception.
This is my called edge function i call within flutter.

```
serve(async (req: Request) => {
  try {
    // Create a Supabase client with the Auth context of the logged in user.
    const supabaseClient = createClient(
      // Supabase API URL - env var exported by default.
      Deno.env.get('SUPABASE_URL') ?? '',
      // Supabase API ANON KEY - env var exported by default.
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      // Create client with Auth context of the user that called the function.
      // This way your row-level-security (RLS) policies are applied.
      { global: { headers: { Authorization: req.headers.get('Authorization')! } } }
    );
    // Now we can get the session or user object
    const {
      data: { user },
    } = await supabaseClient.auth.getUser();

    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );
    const { data: deletion_data, error: deletion_error } = await supabaseAdmin.auth.admin.deleteUser(user.id, true);
    if (deletion_error) throw deletion_error;

    return new Response("User deleted: " + JSON.stringify(deletion_data, null, 2), {
            headers: { "Content-Type": "application/json" },
            status: 200,
          });
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      headers: { 'Content-Type': 'application/json' },
      status: 400,
    });
  }
})
```

Is it wrong to catch the result from deletUser? If so, how do I recognize then if it worked?

```
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: FormatException: Unexpected character (at character 1)
User deleted: "fd4f1aab-76af-41b3-95e8-22048f81defa"
^
flutter:
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
#4      JsonDecoder.convert (dart:convert/json.dart:610:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      jsonDecode (dart:convert/json.dart:155:10)
#7      _compute
_isolates_io.dart:109
<asynchronous suspension>
flutter: ----------------------------------------------------
```
<img width="972" alt="Bildschirmfoto 2023-07-14 um 21 19 09" src="https://github.com/supabase/supabase-flutter/assets/919260/24a734a3-a06c-44f9-9c61-abd670d41803">

The actual exception seems then to be thrown because `_event.next` has a bad state for whatever reason. There is basically no information that points me to the reason.
<img width="781" alt="Bildschirmfoto 2023-07-14 um 21 50 33" src="https://github.com/supabase/supabase-flutter/assets/919260/d46b4288-a218-4de8-a3b3-2f2a8b7bb3a7">

**Comment by Vinzent03** [comment]
Your result from the edge function is not json. You have to wrap it with `{}`

**Comment by Ben1980** [comment]
Thank you that was the cause
