### ISSUE TITLE
signUp() throws FormatException: Unexpected character (at character 1)

### ISSUE THREAD

**Issue by marcoabat** [supabase/supabase-flutter#559]
**Describe the bug**
When I call supabase.auth.signUp in my static DbHelper class, fetch.dart:96  throws FormatException: Unexpected character (at character 1) <!DOCTYPE html>

**Code**
```dart
static Future init() async {
    const url = 'SUPABASE_URL';
    final key = 'SUPABASE_KEY';
    await Supabase.initialize(url: url, anonKey: key ?? '');
}

static SupabaseClient? get _supabase => Supabase.instance.client;

static Future createUser(
      String email, String password, String username) async {
    _supabase!.auth.signUp(email: email, password: password);
}
```
**Stacktrace**

```
E/flutter (30184): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected character (at character 1)
E/flutter (30184): <!DOCTYPE html>
E/flutter (30184): ^
E/flutter (30184):
E/flutter (30184): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
E/flutter (30184): #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250:9)
E/flutter (30184): #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915:22)
E/flutter (30184): #3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
E/flutter (30184): #4      JsonDecoder.convert (dart:convert/json.dart:610:36)
E/flutter (30184): #5      JsonCodec.decode (dart:convert/json.dart:216:41)
E/flutter (30184): #6      GotrueFetch.request
fetch.dart:96
E/flutter (30184): <asynchronous suspension>
E/flutter (30184): #7      GoTrueClient.signUp
gotrue_client.dart:169
E/flutter (30184): <asynchronous suspension>
```

**Version**
supabase_flutter 1.10.9
- supabase 1.9.7
   - functions_client 1.3.2
   - gotrue 1.11.0
   - postgrest 1.3.3
   - realtime_client 1.1.1
   - storage_client 1.5.1

**Additional context**
I'm running supabase locally and sign up worked at first. I didn't make changes to the sign up process after it worked, so I don't really understand where the problem lies. I tried supabase db reset or simplifying my program, but nothing seems to work.

**Comment by marcoabat** [comment]
The issue was that I'm using ngrok to forward localhost and the session ended.
Sorry for the unnecessary issue, I've been searching for a fix for hours.
