### ISSUE TITLE
Project initialization error on IOS

### ISSUE THREAD

**Issue by kpk-i710** [supabase/supabase-flutter#573]
**Describe the bug**
I call before runApp
void main() async {
   await WidgetsFlutterBinding.ensureInitialized();
   await Supabase.initialize(
     url: "https://mysite.supabase.co",
     anonKey: "key...",
   );
   runApp(const MyApp());
}

And I get an error on startup IOS

Performing hot restart...
Syncing files to device iPhone rafael...
Restarted application in 684ms.
flutter: ***** Supabase init completed Instance of 'Supabase'
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:120:24)
<asynchronous suspension>
#2      HiveX.initFlutter (package:hive_flutter/src/hive_extensions.dart:12:18)
<asynchronous suspension>
#3      HiveLocalStorage._initialize (package:supabase_flutter/src/local_storage.dart:92:5)
<asynchronous suspension>
#4      SupabaseAuth.initialize (package:supabase_flutter/src/supabase_auth.dart:99:7)
<asynchronous suspension>
#5      Supabase.initialize (package:supabase_flutter/src/supabase.dart:102:5)
<asynchronous suspension>
#6      main (package:subbase/main.dart:7:3)
<asynchronous suspension>

------------------

Flutter  version -  3.10.6, Mac OS Ventura 13.5 

-------
supabase_flutter: ^1.10.10

**Comment by kpk-i710** [comment]
After deleting the app, the error disappeared.
