### ISSUE TITLE
Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String?' in type cast

### ISSUE THREAD

**Issue by Circl3s** [supabase/supabase-flutter#63]
I'm encountering an unexpected error when subscribing to realtime database changes and I couldn't find anything about it on the web.
```dart
...
final supabase = Supabase.instance;
...

class User {
  String uid;
  late final RealtimeSubscription subscription;

  User({required this.uid}) {
    subscription = supabase.client.from("profiles:id=eq.$uid").on(SupabaseEventTypes.update, (data) {
      stdout.writeln("Updating user $uid");
    });
  }
}
```
The subscription works flawlessly for the first ~30 seconds but then stops working with the following error:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String?' in type cast
#0      RealtimeSubscription.onError.<anonymous closure> (package:realtime_client/src/realtime_subscription.dart:97:42)
#1      RealtimeSubscription.trigger (package:realtime_client/src/realtime_subscription.dart:225:20)
#2      RealtimeClient.onConnMessage.<anonymous closure>.<anonymous closure> (package:realtime_client/src/realtime_client.dart:267:34)
#3      Iterable.forEach (dart:core/iterable.dart:279:35)
#4      RealtimeClient.onConnMessage.<anonymous closure> (package:realtime_client/src/realtime_client.dart:266:60)
#5      new RealtimeClient.<anonymous closure> (package:realtime_client/src/realtime_client.dart:88:21)
#6      RealtimeClient.onConnMessage (package:realtime_client/src/realtime_client.dart:251:11)
#7      RealtimeClient.connect.<anonymous closure> (package:realtime_client/src/realtime_client.dart:110:11)
#8      _rootRunUnary (dart:async/zone.dart:1434:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#13     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#14     _HandleErrorStream._handleData (dart:async/stream_pipe.dart:253:10)
#15     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#16     _rootRunUnary (dart:async/zone.dart:1434:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#21     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#22     _StreamController._add (dart:async/stream_controller.dart:607:7)
#23     _rootRunUnary (dart:async/zone.dart:1434:47)
#24     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#28     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#29     _StreamController._add (dart:async/stream_controller.dart:607:7)
#30     _StreamController.add (dart:async/stream_controller.dart:554:5)
#31     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1144:21)
#32     _rootRunUnary (dart:async/zone.dart:1434:47)
#33     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#39     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:332:23)
#40     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:226:46)
#41     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#42     _rootRunUnary (dart:async/zone.dart:1434:47)
#43     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#44     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#45     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#46     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#47     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#48     _StreamController._add (dart:async/stream_controller.dart:607:7)
#49     _StreamController.add (dart:async/stream_controller.dart:554:5)
#50     _Socket._onData (dart:io-patch/socket_patch.dart:2303:41)
#51     _rootRunUnary (dart:async/zone.dart:1434:47)
#52     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#53     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#54     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#55     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#56     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#57     _StreamController._add (dart:async/stream_controller.dart:607:7)
#58     _StreamController.add (dart:async/stream_controller.dart:554:5)
#59     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1000:19)
#60     _rootRun (dart:async/zone.dart:1418:47)
#61     _CustomZone.run (dart:async/zone.dart:1328:19)
#62     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#63     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#64     _rootRun (dart:async/zone.dart:1426:13)
#65     _CustomZone.run (dart:async/zone.dart:1328:19)
#66     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
#67     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#68     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
#69     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
#70     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```
I'm running Windows 10 (Win32 app), supabase-flutter 0.2.11.

**Comment by Envans** [comment]
Getting the same error and behaviour after upgrading to supabase_flutter 0.2.11

**Comment by clarky2233** [comment]
Getting the same error here

**Comment by phamhieu** [comment]
Duplicated https://github.com/supabase-community/realtime-dart/issues/35

I will close this issue. Please provide a step by step to replicate the error on `realtime-dart` thread. Thank you
