### ISSUE TITLE
init Supabase inside a dart isolate

### ISSUE THREAD

**Issue by chirastefan** [supabase/supabase-flutter#696]
trying to init supabase inside an isolate throws this error
```
[VERBOSE-2:dart_isolate.cc(1097)] Unhandled exception:
UI actions are only available on root isolate.
#0      FfiTrampoline____nativeSetNeedsReportTimings$Method$FfiNative$Ptr (dart:ffi)
#1      PlatformDispatcher.__nativeSetNeedsReportTimings (dart:ui/platform_dispatcher.dart:588:24)
#2      PlatformDispatcher._nativeSetNeedsReportTimings (dart:ui/platform_dispatcher.dart:585:52)
#3      PlatformDispatcher.onReportTimings= (dart:ui/platform_dispatcher.dart:577:29)
#4      SchedulerBinding.addTimingsCallback (package:flutter/src/scheduler/binding.dart:308:26)
#5      SchedulerBinding.initInstances (package:flutter/src/scheduler/binding.dart:240:7)
#6      ServicesBinding.initInstances (package:flutter/src/services/binding.dart:37:11)
#7      PaintingBinding.initInstances (package:flutter/src/painting/binding.dart:20:11)
#8      SemanticsBinding.initInstances (package:flutter/src/semantics/binding.dart:18:11)
#9      RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:29:11)
```

**Comment by richard457** [comment]
@chirastefan  can you point me to a documentation on how to open sperbase in isolate?

**Comment by chirastefan** [comment]
@richard457 I don't remember looking in the documentation for this, I just tried it like this:

```
late final Isolate isolate;

class SomeData {
  final Map<String, String> data;
}

class DBSyncHelperMessage {
  final SendPort port;
  final String endpoint;
  final String anonKey;
  final SomeData data ;

  DBSyncHelperMessage({
    required this.port,
    required this.endpoint,
    required this.anonKey,
    required this.data,
  });
}

  Future<void> spawnIsolate() async {
    final port = ReceivePort();

    isolate = await Isolate.spawn<DBSyncHelperMessage>(
      _spawnHandler,
      DBSyncHelperMessage(
        port: port.sendPort,
        endpoint: endpoint,
        anonKey: anonKey,
        data: null,
      ),
    );
    port.listen((message) {
      switch (message['type']) {
        case 'sync_all_data':
            // logic for sync_all_data
        case 'other_action':
           // logic for other_action
        default:
          break;
      }
    });
  }

  Future<void> _spawnHandler(DBSyncHelperMessage message) async {
    await SupabaseHelper().init(url: message.endpoint, key: message.anonKey);
    // ...
    message.port.send({
      'type': 'sync_all_data',
      'some_data': null
    });
}
```

I hope it helps.

**Comment by richard457** [comment]
are you doing 

loadSupabase() async {
  await Supabase.initialize(
    url: AppSecrets.superbaseurl,
    anonKey: AppSecrets.supabaseAnonKey,
  );
} inside  await SupabaseHelper().init(url: message.endpoint, key: message.anonKey); @chirastefan ?

**Comment by chirastefan** [comment]
`main.dart`

```
await SupabaseHelper().init(url: dotenv.get('BACKEND_ENDPOINT'), key: dotenv.get('BACKEND_ANON_KEY'));
```

where

```
class SupabaseHelper {
  static final SupabaseHelper _instance = SupabaseHelper._();
  static late SupabaseClient client;

  factory SupabaseHelper() => _instance;

  SupabaseHelper._();

  Future<void> init({required String url, required String key}) async {
    await Supabase.initialize(url: url, anonKey: key);
    client = Supabase.instance.client;
  }
}
```
