### ISSUE TITLE
Storage APi mime error

### ISSUE THREAD

**Issue by andim27** [supabase/supabase-flutter#733]
supabase_flutter: ^1.10.24
```
uploadedFileName='GIF-805ee974f78bd53d9c115bc529650d7b.gif';
contentTypeStr = 'image/gif';
sbClient.storage.from(nameStorage).upload(uploadedFileName, file,
            fileOptions: FileOptions(cacheControl: '3600', upsert: false, contentType: "$contentTypeStr"));
ERROR:
```
E/flutter (17175): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: StorageException(message: mime type not supported, statusCode: 422, error: invalid_mime_type)
E/flutter (17175): #0      Fetch._handleResponse (package:storage_client/src/fetch.dart:175:7)
E/flutter (17175): <asynchronous suspension>
E/flutter (17175): #1      StorageFileApi.upload (package:storage_client/src/storage_file_api.dart:54:22)
BUT png, jpg uploaded well

**Comment by andim27** [comment]
May be you are right....
