### ISSUE TITLE
host error

### ISSUE THREAD

**Issue by andim27** [supabase/supabase-flutter#851]
- Not work on real devices but work on emulator Android
-  Supabase on free plan

```
I/flutter (16697): ClientException with SocketException: Failed host lookup: '---myhost---.supabase.co' (OS Error: No address associated with hostname, errno = 7), uri=https://---myhost---.supabase.co/rest/v1/my_table?select=my_data
I/flutter (16697): #0      IOClient.send (package:http/src/io_client.dart:154:7)
I/flutter (16697): <asynchronous suspension>
I/flutter (16697): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
I/flutter (16697): <asynchronous suspension>
I/flutter (16697): #2      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:130:20)
I/flutter (16697): <asynchronous suspension>
I/flutter (16697): #3      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:372:24)
I/flutter (16697): <asynchronous suspension>

```

**Comment by andim27** [comment]
If no internet this error occurs

**Comment by michelemarchetto** [comment]
> If no internet this error occurs

This is not true. The error happens even though internet is working fine.
