### ISSUE TITLE
Postgrest giving stacktrace of only postgrest code

### ISSUE THREAD

**Issue by Jonny1987** [supabase/supabase-flutter#899]
**Describe the bug**
Whenever I use database function on the supabase client (`supabase.rpc` or `supabase.from`) and these throw an error then the stack trace is limited to postgrest code only and non of my app lines (other supabase functions do give a full stacktrace like calling `supabase.signInWithPassword` with an invalid email so I don't think it's my logging setup.

For example:
```
I/flutter ( 4414): PostgrestException(message: Could not find the function public.nearby_venues1(current_lat, current_long, limit_param, utc_offset_minutes_param) in the schema cache, code: PGRST202, details: Searched for the function public.nearby_venues1 with parameters current_lat, current_long, limit_param, utc_offset_minutes_param or with a single unnamed json/jsonb parameter, but no matches were found in the schema cache., hint: Perhaps you meant to call the function public.nearby_venues), #0 PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:283:7)
I/flutter ( 4414): #1 PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:164:14)
I/flutter ( 4414): <asynchronous suspension>
I/flutter ( 4414): #2 PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:372:24)
I/flutter ( 4414): <asynchronous suspension>
```

**To Reproduce**
Call a supabase function which will give an error like `await supabase.rpc('invalid_function')`

**Expected behavior**
The stacktrace should should lines in my app code which led up to the error.

**Comment by dshukertjr** [comment]
This is fair. Will look into it.

**Comment by Jonny1987** [comment]
Any update on this? I will need to find a workaround if not which will probably involve rethrowing a custom error in every place that I use superbase database functions which will be annoying (simply logging isn't enough since like many people, I am using sentry to record errors). Or if you have any ideas about the cause I can try to fix and open a PR

**Comment by Jonny1987** [comment]
I've spent hours looking at the `SupabaseClient` and `PostgrestBuilder` code an I can't see a way to do it other than just doing the following where the supabase function is called:

```
await supabase.rpc('my_function').catchError((error) => throw error);
```

This added some lines from my app to the postgrest stacktrace which is very useful, but annoying to do at every database related call I make.

I dont have a lot of dart experience but it seems that the problem is due to the `PostgrestException` thrown inside `PostgrestBuilder` causing the stacktrace to be limited to `PostgrestBuilder`, and it needs to be rethrown outside that scope for the stacktrace to get lines from outside of the `PostgrestBuilder` code.

The `rpc()` method in `SupabaseClient` returns a `PostgrestFilterBuilder`, so the `catchError` method cannot be used here since this returns a Future.

I feel like there must be another way to do this inside supabase/postgrest code which doesn't require changing my app code but I don't know enough about dart to figure it out.

Is it possible to create method in `PostgrestBuilder` similar to callback as a side effect (or returning the builder itself) rather than returning a new future (which would then need to be returned by the `rpc` method in `SupabaseClient`) then that maybe is an option?

Then the `SupabaseClient.rpc` would do something like:

```
    final builder = rest.rpc(fn, params: params);
    builder.catchErrorCallback((error) => throw error);
    return builder;
```

**Comment by Jonny1987** [comment]
Actually, maybe the following method can be added to `PostgrestFilterBuilder` and `PostgrestQueryBuilder`?

```
  Future<T> end() {
    return this.catchError((error) => throw error);
  }
```

Then in the app code, the developer just needs to append `.end()` to ensure the stacktrace will include local lines:

```
await supabase.rpc('my_function').end();
await supabase.from('profiles').select().eq('id', userId).single().end();
```

@dshukertjr, what are your thoughts?

**Comment by Jonny1987** [comment]
My solution is to create the following file in my own code and import that into files where I do supabase db operations and then append `.end()` to them as above:

```
import 'package:supabase_flutter/supabase_flutter.dart';

extension AddEndMethod on PostgrestBuilder {
  Future end() {
    return catchError((error) => throw error);
  }
}
```

**Comment by dshukertjr** [comment]
Adding `.end()` is a solution that we would like to avoid implementing as it adds a redundant code after every call. 

I took a quick stab at this issue, but couldn't come up with a solution that includes the desired stack trace. 

Although it's not ideal, this issue does have a workaround and is not a critical issue, the priority will be lower than some other issues that we have. With that being said, I will try to see if I can do something about it time to time.

**Comment by minhdanh** [comment]
I'm migrating from Firebase to Supabase. In the middle of the transaction there're many errors that I'm not sure where they are from 😂 
Still, hope this to be fixed.

**Comment by Jonny1987** [comment]
> I'm migrating from Firebase to Supabase. In the middle of the transaction there're many errors that I'm not sure where they are from 😂 Still, hope this to be fixed.

Try using my solution. You just add it to the end of any queries you make and it catches the error inside so you see the stacktrace

eg:
`await Supabase.intance.client.from('mytable').select().end();`

**Comment by minhdanh** [comment]
Thanks for the reply. I tried the solution but it seems not valid anymore:

<img width="1228" alt="Image" src="https://github.com/user-attachments/assets/bfc68957-3142-43a7-b953-9fe0f1961703" />

**Comment by minhdanh** [comment]
At least is there a way to print out which is the troublesome query in postgrest_builder.dart, somewhere here? https://github.com/supabase/supabase-flutter/blob/main/packages/postgrest/lib/src/postgrest_builder.dart#L267-L299

**Comment by spydon** [comment]
@minhdanh you forgot to add the extension from this post: https://github.com/supabase/supabase-flutter/issues/899#issuecomment-2101358093

**Comment by spydon** [comment]
@dshukertjr since this issue is acknowledged, is there a tag to add to it so that it doesn't automatically get closed?

**Comment by spydon** [comment]
Well that was a surprise, that one year later I've actually started working at Supabase and fixing the issue that I had. 😄 
Fix is released in `postgrest` v2.7.1 and bumped in `supabase_flutter` v2.14.2 and `supabase` v2.12.2.
